#!/bin/csh -fv

#------------------------------------------
# *** User sets options in this section ***
#------------------------------------------

### Full path of cesm source code and case (output) directories (see examples)

set CESMDIR=${HOME}/collections/CAM_6_4_120_compass
set CASEDIR=${HOME}/cases

### Case Name

set CASETITLE=f.e30.cam6_4_120
set CASEID=SOCRATES_3days_scam

### Standard Run Settings

set WALLTIME=00:40:00
set RES=ne30_ne30_mg17
set COMPSET=HIST_CAM60%SCAM_CLM50%BGC-CROP_CICE%PRES_DOCN%DOM_SROF_SGLC_SWAV_SESP
set COMPSET_TITLE=FHIST_BGC
#set COMPSET=F2000climo
set COMPILER=intel
#set QUEUE=main
set QUEUE=develop
set PES='--pecount 1'
#set PES=''
set EXP=rf01.cosp

### Run Configuration

set RUN_TYPE=hybrid
# Change this block to run a different flight
set RUN_STARTDATE=2018-01-15
set START_TOD=82200
set PTS_LON=152.658997
set PTS_LAT=-54.957001

set STOP_OPTION=nhours
set STOP_N=10
set REST_OPTION=${STOP_OPTION}
set REST_N=${STOP_N}
set RUN_REFCASE=f.e30.cam6_4_120.FHIST_BGC.ne30_ne30_mg17.SOCRATES_nudgeUVTQsoc_full_withCOSP_tau6h_2months_inithist.100.cosp
set RUN_REFDATE=${RUN_STARTDATE}
set RUN_REFDIR=/glade/derecho/scratch/$USER/cases/${RUN_REFCASE}/run
set GET_REFCASE=TRUE

### SOCRATES FLIGHT TIMES
### Taken from https://doi.org/10.5065/D6M32TM9
#Flight  	Date (UTC)	Time Period (UTC)
#RF01	15 Jan 2018	22:50–06:04
#RF02	19 Jan 2018	00:45–07:45
#RF03	22 Jan 2018	21:00–04:15
#RF04	23 Jan 2018	23:10–06:15
#RF05	25 Jan 2018	22:50–06:00
#RF06	28 Jan 2018	22:50–06:12
#RF07	31 Jan 2018	00:50–08:40
#RF08	03 Feb 2018	23:00–06:55
#RF09	04 Feb 2018	22:50–07:05
#RF10	07 Feb 2018	20:50–05:15
#RF11	17 Feb 2018	01:30–06:17
#RF12	17 Feb 2018	23:40–08:00
#RF13	19 Feb 2018	22:45–06:42
#RF14	21 Feb 2018	22:40–06:48
#RF15	24 Feb 2018	01:50–08:41
#------------------------------------------
# *** User set options continue at the namelist section
#------------------------------------------

#------------------------------------------
# User should not need to set any options in this section
#------------------------------------------

### Make sure that the user has configured a PBS_ACCOUNT environment variable

if ( ! $?PBS_ACCOUNT ) then
    echo "Account must be set as an environment var in your $HOME/.tcshrc file"
    exit
else
    echo "Using account:"
    echo $PBS_ACCOUNT
endif

#Create full casename

cd  $CASEDIR
set CASENAME=${CASETITLE}.${COMPSET_TITLE}.${RES}.${CASEID}.${EXP}

### create case

$CESMDIR/cime/scripts/create_newcase --project $PBS_ACCOUNT --compset $COMPSET  --res $RES --compiler $COMPILER --case $CASEDIR/$CASENAME  --run-unsupported --walltime ${WALLTIME} --queue ${QUEUE} ${PES}

cd  $CASEDIR/$CASENAME

#------------------
# XMLCHANGE OPTIONS HERE from above
#------------------
./xmlchange RUN_TYPE=${RUN_TYPE}
./xmlchange RUN_STARTDATE=${RUN_STARTDATE}
./xmlchange START_TOD=${START_TOD}
./xmlchange STOP_N=${STOP_N}
./xmlchange STOP_OPTION=${STOP_OPTION}
./xmlchange REST_OPTION=${REST_OPTION}
./xmlchange REST_N=${REST_N}
./xmlchange JOB_WALLCLOCK_TIME=${WALLTIME} --subgroup=case.run
./xmlchange RUN_REFDATE=${RUN_REFDATE}
./xmlchange RUN_REFCASE=${RUN_REFCASE}
./xmlchange RUN_REFDIR=${RUN_REFDIR}
./xmlchange GET_REFCASE=${GET_REFCASE}
 
### Append to CAM configure options
./xmlchange ROF_NCPL=`./xmlquery  --value "ATM_NCPL"`
./xmlchange GLC_NCPL=`./xmlquery  --value "ATM_NCPL"`
./xmlchange GMAKE_J=32
./xmlchange DOUT_S=FALSE
./xmlchange --append CAM_CONFIG_OPTS='-cosp'

./xmlchange PTS_DOMAINFILE='/glade/p/cesmdata/inputdata/share/domains/domain.lnd.ne30np4_gx1v6.110905.nc'
./xmlchange LND_DOMAIN_FILE='domain.lnd.ne30np4_gx1v6.110905.nc'
./xmlchange CLM_FORCE_COLDSTART='off'
# User should set the Lat and Lon for SCAM
./xmlchange PTS_LON=${PTS_LON}
./xmlchange PTS_LAT=${PTS_LAT}

### Setup Case
./*setup

#------------------------------------------
# Namelist setup - continue user setup here
#------------------------------------------

cat > user_nl_cam << EOF
inithist = 'yearly'
docosp=.true.
cosp_histfile_num = 3

NDENS    = 1,1
MFILT    = 100,100
nhtfrq   = 1,1
fincl2='T','Q','TDIFF','QDIFF','LANDFRAC'
iopfile ='/glade/derecho/scratch/$USER/rf01.IOP.nc'
ncdata = '/glade/derecho/scratch/$USER/f.e30.cam6_4_120.FHIST_BGC.ne30_ne30_mg17.SOCRATES_nudgeUVTQwindow_withCOSP_tau6h_3days_camiop.rf01.cosp.cam.i.2018-01-15-00000.nc'
inithist = 'YEARLY'
scm_cambfb_mode  = .true.
scm_use_obs_uv   = .true.
scm_use_3dfrc   = .true.
scm_relaxation   = .false.
scale_dry_air_mass              =   0.0D0
write_nstep0           = .true.

ext_frc_specifier              = 'H2O    -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/elev/H2OemissionCH4oxidationx2_3D_L70_1849-2101_CMIP6ensAvg_SSP3-7.0_c190403.nc',
         'num_a1 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_num_so4_a1_anthro-ene_vertical_mol_175001-210101_0.9x1.25_c20190222.nc',
         'num_a1 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/CMIP6_emissions_1750_2015/emissions-cmip6_num_a1_so4_contvolcano_vertical_850-5000_0.9x1.25_c20170724.nc',
         'num_a2 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/CMIP6_emissions_1750_2015/emissions-cmip6_num_a2_so4_contvolcano_vertical_850-5000_0.9x1.25_c20170724.nc',
         'SO2    -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/CMIP6_emissions_1750_2015/emissions-cmip6_SO2_contvolcano_vertical_850-5000_0.9x1.25_c20170724.nc',
         'so4_a1 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_so4_a1_anthro-ene_vertical_mol_175001-210101_0.9x1.25_c20190222.nc',
         'so4_a1 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/CMIP6_emissions_1750_2015/emissions-cmip6_so4_a1_contvolcano_vertical_850-5000_0.9x1.25_c20170724.nc',
         'so4_a2 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/CMIP6_emissions_1750_2015/emissions-cmip6_so4_a2_contvolcano_vertical_850-5000_0.9x1.25_c20170724.nc'
 srf_emis_specifier             = 'bc_a4    -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_bc_a4_anthro_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'bc_a4    -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_bc_a4_bb_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'DMS      -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_DMS_bb_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'DMS      -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-SSP_DMS_other_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'num_a1   -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_num_so4_a1_bb_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'num_a1   -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_num_so4_a1_anthro-ag-ship_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'num_a2   -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_num_so4_a2_anthro-res_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'num_a4   -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_num_bc_a4_bb_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'num_a4   -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_num_bc_a4_anthro_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'num_a4   -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_num_pom_a4_anthro_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'num_a4   -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_num_pom_a4_bb_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'pom_a4   -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_pom_a4_anthro_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'pom_a4   -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_pom_a4_bb_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'SO2      -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_SO2_anthro-ag-ship-res_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'SO2      -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_SO2_anthro-ene_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'SO2      -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_SO2_bb_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'so4_a1   -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_so4_a1_anthro-ag-ship_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'so4_a1   -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_so4_a1_bb_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'so4_a2   -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_so4_a2_anthro-res_surface_mol_175001-210101_0.9x1.25_c20190222.nc',
         'SOAG     -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_SOAGx1.5_anthro_surface_mol_175001-210101_0.9x1.25_c20200403.nc',
         'SOAG     -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp370/emissions-cmip6-ScenarioMIP_IAMC-AIM-ssp370-1-1_SOAGx1.5_bb_surface_mol_175001-210101_0.9x1.25_c20200403.nc',
         'SOAG     -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/emissions_ssp/emissions-cmip6-SOAGx1.5_biogenic_surface_mol_175001-210101_0.9x1.25_c20190329.nc'
tracer_cnst_file               = 'tracer_cnst_halons_3D_L70_1849-2101_CMIP6ensAvg_SSP3-7.0_c190403.nc'
&chem_surfvals_nl
 flbc_file              = '/glade/p/cesmdata/cseg/inputdata/atm/waccm/lb/LBC_2014-2500_CMIP6_SSP370_0p5degLat_GlobAnnAvg_c190301.nc'
 flbc_list              = 'CO2','CH4','N2O','CFC11eq','CFC12'
 flbc_type              = 'SERIAL'
 scenario_ghg           = 'CHEM_LBC_FILE'
/
&prescribed_ozone_nl
 prescribed_ozone_datapath              = '/glade/p/cesmdata/cseg/inputdata/atm/cam/ozone_strataero'
 prescribed_ozone_file          = 'ozone_strataero_WACCM_L70_zm5day_18500101-21010201_CMIP6histEnsAvg_SSP370_c190403.nc'
 prescribed_ozone_name          = 'O3'
 prescribed_ozone_type          = 'SERIAL'
/
&prescribed_strataero_nl
 prescribed_strataero_datapath          = '/glade/p/cesmdata/cseg/inputdata/atm/cam/ozone_strataero'
 prescribed_strataero_file              = 'ozone_strataero_WACCM_L70_zm5day_18500101-21010201_CMIP6histEnsAvg_SSP370_c190403.nc'
 prescribed_strataero_type              = 'SERIAL'
 prescribed_strataero_use_chemtrop              =  .true.
EOF



cat > user_nl_clm << EOFclm
 model_year_align_ndep = 2015
 ndep_taxmode = 'cycle'
 ndep_varlist = 'NDEP_month'
 ndepmapalgo = 'bilinear'
 stream_fldfilename_ndep = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/ndepdata/fndep_clm_f09_g17.CMIP6-SSP3-7.0-WACCM_1849-2101_monthly_c191007.nc'
 stream_year_first_ndep = 2015
 stream_year_last_ndep = 2101
 model_year_align_popdens = 2015
 popdensmapalgo = 'bilinear'
 stream_fldfilename_popdens = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/firedata/clmforc.Li_2018_SSP3_CMIP6_hdm_0.5x0.5_AVHRR_simyr1850-2100_c181205.nc'
 stream_year_first_popdens = 2015
 stream_year_last_popdens = 2100
 model_year_align_urbantv = 2015
 stream_fldfilename_urbantv = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/urbandata/CLM50_tbuildmax_Oleson_2016_0.9x1.25_simyr1849-2106_c160923.nc'
 stream_meshfile_urbantv = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/urbandata/CLM50_tbuildmax_Oleson_2016_0.9x1_ESMFmesh_cdf5_100621.nc'
 stream_year_first_urbantv = 2015
 stream_year_last_urbantv = 2106
 urbantvmapalgo = 'nn'
do_harvest = .true.
do_transient_crops = .true.
do_transient_pfts = .true.
flanduse_timeseries = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_esmf/ctsm5.3.0/landuse.timeseries_ne30np4_SSP2-4.5_1850-2100_78pfts_c240905.nc'
use_init_interp=.true.
EOFclm

#cat > user_nl_cpl << EOFcpl
#reprosum_diffmax=1.0e-14
#reprosum_recompute=.true.
#EOFcpl

#------------------------------------------
# Build
#------------------------------------------
./*.build

mkdir -p $EXEROOT/../run/timing/checkpoints

### Submit to Queue (If you have one)
./case.submit

